blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/quinnjr/leaven/discussions
    about: Ask questions and discuss ideas
  - name: 📖 Documentation
    url: https://leaven.dev
    about: Read the documentation
  - name: 💡 Stack Overflow
    url: https://stackoverflow.com/questions/tagged/leaven-graphql
    about: Ask questions on Stack Overflow
