name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search existing issues before creating a new one.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is this feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like Leaven to...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: API Design
      description: If applicable, provide an example of how you'd like the API to work.
      render: typescript
      placeholder: |
        // Example API usage
        const executor = createExecutor({
          schema,
          newFeature: {
            // ...options
          }
        });

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...

  - type: dropdown
    id: package
    attributes:
      label: Related Package(s)
      description: Which package(s) would this feature belong to?
      multiple: true
      options:
        - '@leaven-graphql/core'
        - '@leaven-graphql/http'
        - '@leaven-graphql/ws'
        - '@leaven-graphql/context'
        - '@leaven-graphql/schema'
        - '@leaven-graphql/errors'
        - '@leaven-graphql/plugins'
        - '@leaven-graphql/playground'
        - '@leaven-graphql/nestjs'
        - 'New package'
        - 'Not sure'

  - type: dropdown
    id: contribution
    attributes:
      label: Would you be willing to contribute this feature?
      options:
        - 'Yes, I can submit a PR'
        - 'Yes, with guidance'
        - 'No, but I can help with testing'
        - 'No'

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request.
      placeholder: Any additional information...
